# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commands.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import geometry2d_pb2 as geometry2d__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63ommands.proto\x12\x18questnav.protos.commands\x1a\x10geometry2d.proto\"R\n ProtobufQuestNavPoseResetPayload\x12.\n\x0btarget_pose\x18\x01 \x01(\x0b\x32\x19.wpi.proto.ProtobufPose2d\"\xcf\x01\n\x17ProtobufQuestNavCommand\x12;\n\x04type\x18\x01 \x01(\x0e\x32-.questnav.protos.commands.QuestNavCommandType\x12\x12\n\ncommand_id\x18\x02 \x01(\r\x12X\n\x12pose_reset_payload\x18\n \x01(\x0b\x32:.questnav.protos.commands.ProtobufQuestNavPoseResetPayloadH\x00\x42\t\n\x07payload\"]\n\x1fProtobufQuestNavCommandResponse\x12\x12\n\ncommand_id\x18\x01 \x01(\r\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t*C\n\x13QuestNavCommandType\x12\x1c\n\x18\x43OMMAND_TYPE_UNSPECIFIED\x10\x00\x12\x0e\n\nPOSE_RESET\x10\x01\x42\x43\n%gg.questnav.questnav.protos.generated\xaa\x02\x19QuestNav.Protos.Generatedb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'commands_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%gg.questnav.questnav.protos.generated\252\002\031QuestNav.Protos.Generated'
  _QUESTNAVCOMMANDTYPE._serialized_start=451
  _QUESTNAVCOMMANDTYPE._serialized_end=518
  _PROTOBUFQUESTNAVPOSERESETPAYLOAD._serialized_start=62
  _PROTOBUFQUESTNAVPOSERESETPAYLOAD._serialized_end=144
  _PROTOBUFQUESTNAVCOMMAND._serialized_start=147
  _PROTOBUFQUESTNAVCOMMAND._serialized_end=354
  _PROTOBUFQUESTNAVCOMMANDRESPONSE._serialized_start=356
  _PROTOBUFQUESTNAVCOMMANDRESPONSE._serialized_end=449
# @@protoc_insertion_point(module_scope)
