# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


#import geometry2d_pb2 as geometry2d__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x14questnav.protos.data\x1a\x10geometry2d.proto\"n\n\x19ProtobufQuestNavFrameData\x12\x13\n\x0b\x66rame_count\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x01\x12)\n\x06pose2d\x18\x03 \x01(\x0b\x32\x19.wpi.proto.ProtobufPose2d\"p\n\x1aProtobufQuestNavDeviceData\x12\x1d\n\x15tracking_lost_counter\x18\x01 \x01(\x05\x12\x1a\n\x12\x63urrently_tracking\x18\x02 \x01(\x08\x12\x17\n\x0f\x62\x61ttery_percent\x18\x03 \x01(\x05\x42\x43\n%gg.questnav.questnav.protos.generated\xaa\x02\x19QuestNav.Protos.Generatedb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%gg.questnav.questnav.protos.generated\252\002\031QuestNav.Protos.Generated'
  _PROTOBUFQUESTNAVFRAMEDATA._serialized_start=54
  _PROTOBUFQUESTNAVFRAMEDATA._serialized_end=164
  _PROTOBUFQUESTNAVDEVICEDATA._serialized_start=166
  _PROTOBUFQUESTNAVDEVICEDATA._serialized_end=278
# @@protoc_insertion_point(module_scope)
