# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geometry3d.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10geometry3d.proto\x12\twpi.proto\"8\n\x15ProtobufTranslation3d\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"@\n\x12ProtobufQuaternion\x12\t\n\x01w\x18\x01 \x01(\x01\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\t\n\x01z\x18\x04 \x01(\x01\">\n\x12ProtobufRotation3d\x12(\n\x01q\x18\x01 \x01(\x0b\x32\x1d.wpi.proto.ProtobufQuaternion\"x\n\x0eProtobufPose3d\x12\x35\n\x0btranslation\x18\x01 \x01(\x0b\x32 .wpi.proto.ProtobufTranslation3d\x12/\n\x08rotation\x18\x02 \x01(\x0b\x32\x1d.wpi.proto.ProtobufRotation3d\"}\n\x13ProtobufTransform3d\x12\x35\n\x0btranslation\x18\x01 \x01(\x0b\x32 .wpi.proto.ProtobufTranslation3d\x12/\n\x08rotation\x18\x02 \x01(\x0b\x32\x1d.wpi.proto.ProtobufRotation3d\"Y\n\x0fProtobufTwist3d\x12\n\n\x02\x64x\x18\x01 \x01(\x01\x12\n\n\x02\x64y\x18\x02 \x01(\x01\x12\n\n\x02\x64z\x18\x03 \x01(\x01\x12\n\n\x02rx\x18\x04 \x01(\x01\x12\n\n\x02ry\x18\x05 \x01(\x01\x12\n\n\x02rz\x18\x06 \x01(\x01\x42\x1a\n\x18\x65\x64u.wpi.first.math.protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'geometry3d_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030edu.wpi.first.math.proto'
  _PROTOBUFTRANSLATION3D._serialized_start=31
  _PROTOBUFTRANSLATION3D._serialized_end=87
  _PROTOBUFQUATERNION._serialized_start=89
  _PROTOBUFQUATERNION._serialized_end=153
  _PROTOBUFROTATION3D._serialized_start=155
  _PROTOBUFROTATION3D._serialized_end=217
  _PROTOBUFPOSE3D._serialized_start=219
  _PROTOBUFPOSE3D._serialized_end=339
  _PROTOBUFTRANSFORM3D._serialized_start=341
  _PROTOBUFTRANSFORM3D._serialized_end=466
  _PROTOBUFTWIST3D._serialized_start=468
  _PROTOBUFTWIST3D._serialized_end=557
# @@protoc_insertion_point(module_scope)
